### PR TITLE
Add en/fr sections in "CCS code snippets" for instructions on how to use a local background image

### PR DESCRIPTION
**Pull request by raphraph**
Title is explicit I hope :)

NB : this is my first pull request, I made a small change to the doc because I had to search myself on how to use a local background image instead of an online image so I thought it could be useful for others. Any advice/feedback is welcome.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Hey, very good idea indeed! But I'm thinking maybe it would be even more clear if we adapt the title of the section above (Not "Use Random Unsplash Images" but rather "Use Background Images" or something along these lines), and add a blockquote (which will render as an info-block) below indicating something like "Note that you can also use local background images if you want to" and add the information by you there?

This would keep these together as the only thing that changes between these two ideas would be exactly that. Or do you think this could be confusing for people not used to using CSS? (I mean I'm the developer, so I'm pretty blind as to what actually helps other people!)

**Comment by raphraph** [comment]
Actually I hesitated on doing what you propose :)
But then I went for what was simplest for me because I thought that I would need to "reorganize" the unsplash background image section...
I'm OK to adapt the title section and add a blockquote. I don't think it will be particularly confusing, people who will do this will at least probably have (like me) a basic knowledge of how to use css and what it is but not using it enough to be able to do this kind of changes without looking for help somewhere.

**Comment by nathanlesage** [comment]
Alright, that's good to hear! You're actually the expert on this, and not me, so I'll trust your judgment when it comes to conveying this information in the documentation :)

**Comment by raphraph** [comment]
Ok I made the changes.

**Comment by nathanlesage** [comment]
Perfect, thanks so much!

**Pull request merged**
