### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by IulekShi**
Obviously first time using GitHub. Hope it will go well!

### CODE REVIEW

**Comment by nathanlesage** [comment]
Oh my God, this is amazing! Thanks so much for this really hard work in translating **all** of the documentation! Almost everything looks very good!  I also tried it out and it builds perfectly.

However, two very small things:

1. There's an `.RHistory`-file that should not be committed to the repository (it's empty either way!)
2. The `index.htm` doesn't work out, because a lot of the styling is gone.

For point two, it's very easy to fix that: Simply edit the file directly here on GitHub (so that, if I see this correctly, TextEdit?, cannot interfere), and copy over [the existing index.html](https://github.com/Zettlr/zettlr-docs/blob/master/assets/index.html), and only add one single line at the respective position:

```html
<li><a href="/it"><span class="flag">🇮🇹</span> Italiano</a></li>
```

[This link should work to edit the file](https://github.com/IulekShi/zettlr-docs/edit/Italian-Docs/assets/index.html)!

The rest is perfect, and I'll gladly merge this! :)

**Comment by IulekShi** [comment]
Hi,
I hope I did what you were expecting in adding that line.

Thanks to you for your amazing job in conceiving, creating and maintaining Zettlr. It really is changing how I'm working since I've discovered it!

I'm no programmer but maybe I'll find other ways to contribute in the future!

**Comment by nathanlesage** [comment]
I've just incorporated the changes myself, as I just found out I could! And now it's merged, thank you very much again for your efforts! :)

**Comment by IulekShi** [comment]
I thought I did those changes, but apparently not! 😅
Thanks to you, glad to have contributed to your amazing project!

**Pull request merged**
