### PR TITLE
rename "shortcuts" to "keyboard shortcuts"

### PR DESCRIPTION
**Pull request by caseywatts**
I had some trouble finding this page at first when I searched for "keyboard" - I kept finding the Tables page, and it wasn't until I manually read through the whole table of contents that I found "shortcuts" which looked promising.

This change should help other people find keyboard shortcuts more easily too :)

### CODE REVIEW

**Comment by nathanlesage** [comment]
Clever thinking! Thanks!

**Comment by canpolat** [comment]
@caseywatts  @nathanlesage This PR broke the menu due to renaming of the file. Either the filename should be reverted, or the menu should be fixed. I think reverting the filename is the easiest option here (due to translations).

**Comment by canpolat** [comment]
I see that this has been quickly fixed 👍

**Comment by nathanlesage** [comment]
Yes, it was another PR and I figured it out when there were actually no merge issues when I did it on the command line 😄

**Pull request merged**
