### PR TITLE
Docs in Spanish

### PR DESCRIPTION
**Pull request by ScaredCoward**
Hello all.

This fork is the docs in Spanish.
- as is, with probably a heap of mistakes and issues
- naming:
    - FOLDERS: in English
    - FILES: English with `-es`added: `filename-es.extension`, e.g. `markdown-basics-es.md`
    - LINKS: internal links look like this `[documentación de Markdown](reference/markdown-basics-es.md)`
    - IMAGES: untouched
- I never githubbed before:
image

### CODE REVIEW

**Comment by nathanlesage** [comment]
First time I've seen a meme on here, nice!

As to your request: I find it impressive that you've done this in such a short amount of time, thank you very much! Translation of the docs is also something that has been mentioned somewhere in the issue tracker of Zettlr and I perfectly see the need and all benefits of it.

However: Currently with MkDocs it's not really possible. My own opinion is to head over to their repository and see to fixing https://github.com/mkdocs/mkdocs/issues/211. Once that is implemented and in Master, we can pull in all localisations, including yours! I would like it that way because it would not involve monkey patching of the software!

Any opinions? :)

**Comment by ScaredCoward** [comment]
Hello,

what if you linked to this [Menu en Español](https://github.com/ScaredCoward/zettlr-docs/blob/master/Menu%20en%20ESPA%C3%91OL.md) from some place busy?

It might not look nice but it might help and get the localisation some exposure.

Best!

**Comment by nathanlesage** [comment]
Ouhh, clever! Yes, this would be a good workaround, I'll add it to the default version of the docs! :)
Let's hope we can merge the Spanish translation fast, I've already given the MkDocs issues some exposure, maybe it helps …!

(I'll keep the pull request open to show other people that someone's already doing a great amount of work. Thanks again!)

**Comment by nathanlesage** [comment]
It's live! (Please tell me it's more or less correct Spanish 🙈)

**Comment by ScaredCoward** [comment]
Thanks, seen it.

As for ESP: Well, I'd say it is not gibberish.

Issues would be: 

- this is es-ES, more beautiful variants exist
- sneaky, sneaky typos, 
- you translate what you understand; maybe easier phrasing is possible in places
- much of the computer lingo used in Spain is in ESP and not in ENG, as e.g. Northern European countries
- ...

Of course, translations are a tricky business so I can understand your concerns: [My hovercraft is full of eels](https://www.urbandictionary.com/define.php?term=My%20hovercraft%20is%20full%20of%20eels)

;)

**Comment by nathanlesage** [comment]
Heya!

I finally decided I don't want to wait for MKDocs to finally enable multi-language support so I did it myself! So if you'd like, you can adapt the Spanish translation to fit the description given in `README.md` (if you have any questions please ask!) and I can _finally_ merge your PR! :)

**Comment by nathanlesage** [comment]
@ScaredCoward As this PR now has its first birthday, I'd like to again hope that you see this issue and maybe even volunteer to merge the spanish docs? :)

**Comment by nathanlesage** [comment]
After more than a year, I'm closing this. But I hope that the Spanish docs will make it back into the "real" documentation soon.

**Pull request closed without merging**
