### PR TITLE
Update localisation.md - remove broken link

### PR DESCRIPTION
**Pull request by marcelorsr**
The link at "the GitHub user wooorm has an extensive set", pointing to https://github.com/wooorm/dictionaries/tree/master/dictionaries, is broken.

### CODE REVIEW

**Comment by nathanlesage** [comment]
I don't know what has happened, but this link here works: https://github.com/wooorm/dictionaries

**Comment by wooorm** [comment]
It’s `main` now

**Comment by nathanlesage** [comment]
> It’s `main` now

Found that out as well afterwards — we might adapt the link as such instead of removing it.

**Comment by marcelorsr** [comment]
Sure, sorry for not noticing it was available somewhere else. Changing the link is the better option, of course.

**Comment by nathanlesage** [comment]
Do you want to change that or shall I?

**Comment by marcelorsr** [comment]
Please, do it. I'm still not that familiar with GitHub, anyway. Thanks a lot for your great work, by the way!

**Comment by nathanlesage** [comment]
Alright, I'll do it! :)

**Pull request closed without merging**
