### PR TITLE
Add a remark about use of tabs in YAML frontmatter

### PR DESCRIPTION
**Pull request by canpolat**

### CODE REVIEW

**Comment by nathanlesage** [comment]
Good thinking, but we should also make sure Zettlr doesn't insert tabs, because why the heck!

**Comment by canpolat** [comment]
Do you mean Zettlr should detect that the user is writing in the YAML frontmatter and then convert tabs into spaces? That may be tricky, because it is possible that user has not yet inserted the closing `---` or `...` yet. So, it may be impossible to reliably detect it. (Unless you want to treat everything after a `---` in the first line as YAML frontmatter until the closing characters appear.) I think the squiggly lines are -kind of- good enough. But I will not stop you from implementing a fix :D

**Comment by nathanlesage** [comment]
> Do you mean Zettlr should detect that the user is writing in the YAML frontmatter and then convert tabs into spaces?

It should generally add spaces instead of tabs, and we just have to find out why CodeMirror is set to add Tab characters instead of Spaces … don't worry, it's not impossible to detect, it's just a misconfiguration \*somewhere\* …

**Comment by canpolat** [comment]
Do you want me to create a bug for that?

**Comment by nathanlesage** [comment]
Sure, feel free! And if you feel like it, a PR, in case you have time + find the issue!

**Comment by canpolat** [comment]
I almost never develop anything in JavaScript, so I will probably postpone that until a day I feel braver. But the bug is in place: https://github.com/Zettlr/Zettlr/issues/1097

**Pull request merged**
