### PR TITLE
Add a note about using spaces in keywords

### PR DESCRIPTION
**Pull request by canpolat**

### CODE REVIEW

**Comment by canpolat** [comment]
If I understand this correctly, if a keyword contains spaces, it has to be enclosed in quotation marks, otherwise Zettlr will not recognize the keyword correctly.

**Comment by nathanlesage** [comment]
> If I understand this correctly, if a keyword contains spaces, it has to be enclosed in quotation marks, otherwise Zettlr will not recognize the keyword correctly.

No, `#"keyword with spaces"` does not work. To use spaces in keywords, one needs to use the [`keywords`-property in the YAML frontmatter](https://docs.zettlr.com/en/core/yaml-frontmatter/#variable-keywords).

**Comment by canpolat** [comment]
I guess the wording can be more clear, but this note is already in the "keywords" sub-section of "YAML front-matter" section. Will take another look when I have some more time.

**Comment by canpolat** [comment]
Looks like I have misunderstood the whole thing. I changed the note to warn the user about the consequences of using spaces in a keyword using an image, but I'm not sure this is the correct place to do this. The whole thing started looking too verbose/wordy and I'm in favor of abandoning this PR.

**Comment by nathanlesage** [comment]
Well, I do not really get the current state of this PR, so maybe you're right …

**Pull request closed without merging**
