### PR TITLE
Updated pages with Discord links and draft of pomodoro docs

### PR DESCRIPTION
**Pull request by break6700**
My first commit to working on the Zettlr docs. I am not sure if this is the appropriate style of writing to use and it may be a little convoluted but I hope it is helpful. :slightly_smiling_face:

### CODE REVIEW

**Comment by nathanlesage** [comment]
The screenshots you took show me once again that I have to go into the Linux styling, because … that slider looks ugly 🙈

But other than that, thank you for the efforts! There are a few typos and I personally would make the sentences simpler (especially preventing passive voice, you have at one point something like "the button is clicked again" instead of "click the button again"). But other than that, this already looks good and I am looking forward to your help! :)

**Comment by break6700** [comment]
I think the passive voice comes from my assignment writing. I have to get out of the habit for general writing.

Also, what form of English would you like? I notice most of the documentation is in English UK (my preferred) but in some places spellings like 'color' is used which is US based.

**Comment by break6700** [comment]
My second attempt without passive voice, simpler language and with UK spelling.

**Comment by nathanlesage** [comment]
Looks good! :)

In case you spot some typos later, don't worry and just open another PR! :)

**Pull request merged**
