### PR TITLE
Extend setup of local work environment

### PR DESCRIPTION
**Pull request by tobiasdiez**
Extend commands that need to be run in order to have a successful local build.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Hey, thanks for the PR! I didn't realize I had forgotten to update this thingy for so long!

How about copying over the initial-setup-stuff from the current state of the README? Because there I already updated this. Nevertheless, the documentation of the commands is also something we should add here (e.g. why wp:prod and wp:dev, etc.). Plus, I'd like to remove the CSL styles and CSL translations from git in the near future to keep the repository leaner, so it would be appropriate to add these commands there was well …

Opinions? :)

**Comment by tobiasdiez** [comment]
I did copied the commands from the current readme. Or do you mean that I should copy the exact same phrasing? I didn't include the description of the commands as this is covered a bit further down in the document anyway. 

What about adding a central `build:prepare/setup` command that invokes all the necessary commands in the right order? Would also make it a bit easier in the future development as these commands should be invoked after each checkout, right?

**Comment by nathanlesage** [comment]
> Or do you mean that I should copy the exact same phrasing?

Not necessarily. What I wanted to point out is that in the README I just had the `install`-commands, and then the pre-compilation messages separately, because I didn't want to copy all the things simply exchanging `yarn` with `npm run`. Besides, I just realised that we might want to discuss whether or not to completely discourage `npm` and only enforce `yarn` (because no npm-lockfiles are committed as of now) or if we should provide both npm _and_ yarn lockfiles (I'd opt for number one due to simplicity). If we choose to discourage npm, we could drop all the `npm`-stuff, because people who want to use that will know to exchange `yarn` with `npm run` either way — this would also make the README simpler.

Concerning the central command: This is actually a good idea. We could even add that one to the `postinstall`-section to be run automatically after `install`s, if I'm not mistaken, right? This would make the section _even leaner_. And then we could only say "Please run `install`" and then only list the commands and describe them!

**Comment by nathanlesage** [comment]
Hey, just saw this PR again (I'm not often here <.<) and as we've already worked on the development stuff so much … is this still relevant?

**Pull request closed without merging**
