### PR TITLE
Added missing options to citations page

### PR DESCRIPTION
**Pull request by break6700**
Added Better BibLaTeX and Better BibTeX options to citations page. I am unable to update screen shots to page as I cannot add example paths e.g. `path/to/your/json`.

### CODE REVIEW

**Comment by break6700** [comment]
Ah I thought I tested BibLaTeX support, clearly I was mistaken.

In the original documentation it shows an example paths e.g. path/to/your/database.json

image

But if I try to add the example path for a screen shot in Zettlr it (correctly) doesn't allow me to type in a path and instead opens a file explorer so I can choose the file.

image

**Comment by break6700** [comment]
> Other than that, the only thing I can see is that you also mentioned that BibLaTeX export can be used. However, Astrocite doesn't yet ship with BibLaTeX support, only BibTeX. So Zettlr can't read that format unfortunately...

> Ah I thought I tested BibLaTeX support, clearly I was mistaken.

I've just tried exporting with Better BibLaTeX and (as it supports a `.bib` file) Zettlr does accept it and displays correctly after being exported as a PDF.

**Comment by nathanlesage** [comment]
@break6700 Yes, Pandoc supports BibLaTeX. But the citation preview within Zettlr doesn't. So you can use BibLaTeX, but only at the cost of having non-functional previews inside the app. You can certainly add this caveat as a note (that is: Use a Markdown blockquote for the info, something like "You can also use BibLaTeX libraries, since they are supported during export. However, then the preview within the app won't work")

**Comment by break6700** [comment]
Ah yes, I see it (although it does appear to the user as a correct citation is made). I will change it now.

**Pull request closed without merging**
